### ISSUE TITLE
test-charpoly failure (Danilevskii variant)

### ISSUE THREAD

**Issue by d-torrance** [linbox-team/fflas-ffpack#330] opened 2021-03-11 10:46 UTC
From a [PPA build on amd64 in Ubuntu 20.10](https://launchpadlibrarian.net/527328266/buildlog_ubuntu-groovy-amd64.fflas-ffpack_2.4.3.12.g15a2cc42-0ppa1~ubuntu20.10.1_BUILDING.txt.gz):

```
FAIL: test-charpoly
===================

Checking ..............Danilevskii variant over ModularBalanced<float> mod 1069...PASSED
Checking .................LUKrylov variant over ModularBalanced<float> mod 1069...PASSED
Checking .......Precond. ArithProg variant over ModularBalanced<float> mod 1069...PASSED
Checking .........Automated variant choice over ModularBalanced<float> mod 1069...PASSED
Checking ..............Danilevskii variant over ModularBalanced<float> mod 5449...PASSED
Checking .................LUKrylov variant over ModularBalanced<float> mod 5449...PASSED
Checking .......Precond. ArithProg variant over ModularBalanced<float> mod 5449...PASSED
Checking .........Automated variant choice over ModularBalanced<float> mod 5449...PASSED
Checking Danilevskii variant over Modular_implem<float, float, uint32_t> modulo 1069...PASSED
Checking LUKrylov variant over Modular_implem<float, float, uint32_t> modulo 1069...PASSED
Checking Precond. ArithProg variant over Modular_implem<float, float, uint32_t> modulo 1069...PASSED
Checking Automated variant choice over Modular_implem<float, float, uint32_t> modulo 1069...PASSED
Checking Danilevskii variant over Modular_implem<float, float, uint32_t> modulo 1367...PASSED
Checking LUKrylov variant over Modular_implem<float, float, uint32_t> modulo 1367...PASSED
Checking Precond. ArithProg variant over Modular_implem<float, float, uint32_t> modulo 1367...PASSED
Checking Automated variant choice over Modular_implem<float, float, uint32_t> modulo 1367...PASSED
Checking ......Danilevskii variant over ModularBalanced<double> mod 1.46563e+08...PASSED
Checking .........LUKrylov variant over ModularBalanced<double> mod 1.46563e+08...PASSED
Checking Precond. ArithProg variant over ModularBalanced<double> mod 1.46563e+08...PASSED
Checking .Automated variant choice over ModularBalanced<double> mod 1.46563e+08...PASSED
Checking ......Danilevskii variant over ModularBalanced<double> mod 1.74577e+08...PASSED
Checking .........LUKrylov variant over ModularBalanced<double> mod 1.74577e+08...PASSED
Checking Precond. ArithProg variant over ModularBalanced<double> mod 1.74577e+08...PASSED
Checking .Automated variant choice over ModularBalanced<double> mod 1.74577e+08...PASSED
Checking Danilevskii variant over Modular_implem<double, double, uint64_t> modulo 64046117...PASSED
Checking LUKrylov variant over Modular_implem<double, double, uint64_t> modulo 64046117...PASSED
Checking Precond. ArithProg variant over Modular_implem<double, double, uint64_t> modulo 64046117...PASSED
Checking Automated variant choice over Modular_implem<double, double, uint64_t> modulo 64046117...PASSED
Checking Danilevskii variant over Modular_implem<double, double, uint64_t> modulo 40359251...PASSED
Checking LUKrylov variant over Modular_implem<double, double, uint64_t> modulo 40359251...PASSED
Checking Precond. ArithProg variant over Modular_implem<double, double, uint64_t> modulo 40359251...PASSED
Checking Automated variant choice over Modular_implem<double, double, uint64_t> modulo 40359251...PASSED
Checking ...........Danilevskii variant over ModularBalanced<int32_t> mod 83003...PASSED
Checking ..............LUKrylov variant over ModularBalanced<int32_t> mod 83003...PASSED
Checking ....Precond. ArithProg variant over ModularBalanced<int32_t> mod 83003...PASSED
Checking ......Automated variant choice over ModularBalanced<int32_t> mod 83003...PASSED
Checking ..........Danilevskii variant over ModularBalanced<int32_t> mod 120121...PASSED
Checking .............LUKrylov variant over ModularBalanced<int32_t> mod 120121...PASSED
Checking ...Precond. ArithProg variant over ModularBalanced<int32_t> mod 120121...PASSED
Checking .....Automated variant choice over ModularBalanced<int32_t> mod 120121...PASSED
Checking Danilevskii variant over Modular_implem<int32_t, uint32_t, uint32_t> modulo 17467...PASSED
Checking LUKrylov variant over Modular_implem<int32_t, uint32_t, uint32_t> modulo 17467...PASSED
Checking Precond. ArithProg variant over Modular_implem<int32_t, uint32_t, uint32_t> modulo 17467...PASSED
Checking Automated variant choice over Modular_implem<int32_t, uint32_t, uint32_t> modulo 17467...PASSED
Checking Danilevskii variant over Modular_implem<int32_t, uint32_t, uint32_t> modulo 13339...PASSED
Checking LUKrylov variant over Modular_implem<int32_t, uint32_t, uint32_t> modulo 13339...PASSED
Checking Precond. ArithProg variant over Modular_implem<int32_t, uint32_t, uint32_t> modulo 13339...PASSED
Checking Automated variant choice over Modular_implem<int32_t, uint32_t, uint32_t> modulo 13339...PASSED
Checking ......Danilevskii variant over ModularBalanced<int64_t> mod 2882618423...PASSED
Checking .........LUKrylov variant over ModularBalanced<int64_t> mod 2882618423...PASSED
Checking Precond. ArithProg variant over ModularBalanced<int64_t> mod 2882618423...PASSED
Checking .Automated variant choice over ModularBalanced<int64_t> mod 2882618423...PASSED
Checking ......Danilevskii variant over ModularBalanced<int64_t> mod 4469544263...PASSED
Checking .........LUKrylov variant over ModularBalanced<int64_t> mod 4469544263...PASSED
Checking Precond. ArithProg variant over ModularBalanced<int64_t> mod 4469544263...PASSED
Checking .Automated variant choice over ModularBalanced<int64_t> mod 4469544263...PASSED
Checking Danilevskii variant over Modular_implem<int64_t, uint64_t, uint64_t> modulo 2882618423...PASSED
Checking LUKrylov variant over Modular_implem<int64_t, uint64_t, uint64_t> modulo 2882618423...PASSED
Checking Precond. ArithProg variant over Modular_implem<int64_t, uint64_t, uint64_t> modulo 2882618423...PASSED
Checking Automated variant choice over Modular_implem<int64_t, uint64_t, uint64_t> modulo 2882618423...PASSED
Checking Danilevskii variant over Modular_implem<int64_t, uint64_t, uint64_t> modulo 174576979...FAILED: trace = 166756712 P[149] = 156350171
 P = [139276646 124389217 122188359 117204469 32376234 170845349 23104561 16551796 124271741 118377579 143474702 23008088 69554432 18829307 66091654 48412292 100106276 51536511 373242 110292462 154492191 23063270 166948645 20289286 112520208 73617114 57779405 141733156 48590750 10620735 51755350 107925176 104618524 145866727 140751404 20288094 29831616 94438300 95547660 53409152 105827106 51499921 30454973 30273381 65920966 148193915 156077307 113683620 120870520 140351672 127096833 84757185 109494783 138128006 23137240 52773184 50409466 95195488 35204717 96448654 24235829 76347087 135845314 113389576 80097032 33729216 108896618 76508321 30420669 140998079 120370831 74355336 66708265 148457911 108282407 147414987 22782387 163115136 2138043 168043491 19664963 49390864 135704972 157838332 96665019 5260635 17628270 59358684 76237777 57754902 28392739 92916902 96914210 106669456 139601191 157541680 104091629 49219174 142885293 112601694 90221367 79167818 67761450 107509673 151358687 106520384 57798631 131345047 137262406 17572522 70055819 77699764 160201369 135894196 40875206 7040339 4967037 94027997 130593725 13133443 138693679 40099163 79227337 63002416 9188414 51524413 62067034 59863940 140897244 17883552 86616544 163041906 64983389 109757690 58873196 118873597 135234678 166465526 82391126 152771638 149483966 168647204 85274579 137006389 96913802 74022627 172753421 140085608 19700463 156350171 1 ]

Failed with seed = 204270724
FAIL test-charpoly (exit status: 1)
```

**Comment by ClementPernet** [comment] 2021-03-25 11:37
Likely coming from the bug in #307 
I could reproduce it, and it now no longer apeears  since  9d78b89 which fixed #307 
Hence closing.

**Closed by ClementPernet** 2021-03-25 11:37 UTC
